In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('liulang.csv', names=['Num','nickname','link','img_link','start','eval','votes','data','comments'],skiprows=[0])

In [5]:
df.head()

Num nickname                                           link  \
0    0       侠侠        https://www.douban.com/people/40082523/   
1    1       影志          https://www.douban.com/people/tjz230/   
2    2  嘟嘟熊之父 🧸  https://www.douban.com/people/duduxiongzhifu/   
3    3      陆支羽         https://www.douban.com/people/luzhiyu/   
4    4     沙雕电影       https://www.douban.com/people/185573840/   

                                          img_link  start eval  votes  \
0   https://img3.doubanio.com/icon/u40082523-2.jpg     10   很差  35972   
1  https://img1.doubanio.com/icon/u1005928-127.jpg     40   推荐  66841   
2   https://img3.doubanio.com/icon/u2201715-15.jpg     10   很差  67180   
3  https://img3.doubanio.com/icon/u2866549-132.jpg     50   力荐  58208   
4  https://img3.doubanio.com/icon/u185573840-2.jpg     40   推荐  32570   

                                                data  \
0  \r\n                    2019-02-05\r\n        ...   
1  \r\n                    2019-02-04\r\n        ...   
2  \r\n                    2019-01-28\r\n        ...   
3  \r\n                    2019-01-29\r\n        ...   
4  \r\n                    2019-02-05\r\n        ...   

                                            comments  
0  真为吴京的演技尴尬，总是摆出一副大义凌然的样子，好奇为什么刘的作品中总有这种傻逼般的圣母存在...  
1  电影比预期要更恢弘磅礴，晨昏线过后的永夜、火种计划、让地球流浪、木星推动地球…等等大小设定，...  
2  还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...  
3  1.终于，轮到我们仰望星空。2.后启示录死亡废墟，赛博朋克地下城，以及烟波浩渺的末日想象，缔...  
4            一个悲伤的故事：太阳都要毁灭，地球都要流浪了，我国的校服还是这么丑......

In [6]:
def make_label(df):
    df["sentiment"] = df["start"].apply(lambda x: 1 if x>30 else 0)

In [7]:
make_label(df)

In [21]:
df.head()

Num nickname                                           link  \
0    0       侠侠        https://www.douban.com/people/40082523/   
1    1       影志          https://www.douban.com/people/tjz230/   
2    2  嘟嘟熊之父 🧸  https://www.douban.com/people/duduxiongzhifu/   
3    3      陆支羽         https://www.douban.com/people/luzhiyu/   
4    4     沙雕电影       https://www.douban.com/people/185573840/   

                                          img_link  start eval  votes  \
0   https://img3.doubanio.com/icon/u40082523-2.jpg     10   很差  35972   
1  https://img1.doubanio.com/icon/u1005928-127.jpg     40   推荐  66841   
2   https://img3.doubanio.com/icon/u2201715-15.jpg     10   很差  67180   
3  https://img3.doubanio.com/icon/u2866549-132.jpg     50   力荐  58208   
4  https://img3.doubanio.com/icon/u185573840-2.jpg     40   推荐  32570   

                                                data  \
0  \r\n                    2019-02-05\r\n        ...   
1  \r\n                    2019-02-04\r\n        ...   
2  \r\n                    2019-01-28\r\n        ...   
3  \r\n                    2019-01-29\r\n        ...   
4  \r\n                    2019-02-05\r\n        ...   

                                            comments  sentiment  
0  真为吴京的演技尴尬，总是摆出一副大义凌然的样子，好奇为什么刘的作品中总有这种傻逼般的圣母存在...          0  
1  电影比预期要更恢弘磅礴，晨昏线过后的永夜、火种计划、让地球流浪、木星推动地球…等等大小设定，...          1  
2  还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...          0  
3  1.终于，轮到我们仰望星空。2.后启示录死亡废墟，赛博朋克地下城，以及烟波浩渺的末日想象，缔...          1  
4            一个悲伤的故事：太阳都要毁灭，地球都要流浪了，我国的校服还是这么丑......          1

In [22]:
X = df[['comments']]
y = df.sentiment

In [23]:
X.shape

(30000, 1)

In [24]:
y.shape

(30000,)

In [25]:
X.head()

comments
0  真为吴京的演技尴尬，总是摆出一副大义凌然的样子，好奇为什么刘的作品中总有这种傻逼般的圣母存在...
1  电影比预期要更恢弘磅礴，晨昏线过后的永夜、火种计划、让地球流浪、木星推动地球…等等大小设定，...
2  还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...
3  1.终于，轮到我们仰望星空。2.后启示录死亡废墟，赛博朋克地下城，以及烟波浩渺的末日想象，缔...
4            一个悲伤的故事：太阳都要毁灭，地球都要流浪了，我国的校服还是这么丑......

In [26]:
import jieba

In [27]:
def chinese_word_cut(mytext):
    return " ".join(jieba.cut(mytext))

In [28]:
X['cutted_comment'] = X.comments.apply(chinese_word_cut)

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  """Entry point for launching an IPython kernel.


In [29]:
X.cutted_comment[:5]

0    真为 吴京 的 演技 尴尬 ， 总是 摆 出 一副 大义 凌然 的 样子 ， 好奇 为什么 ...
1    电影 比 预期 要 更 恢弘 磅礴 ， 晨昏 线 过后 的 永夜 、 火种 计划 、 让 地...
2    还 能 更 土 更 儿戏 一点 吗 ？ 毫无 思考 仅靠 煽动 ， 毫无 敬畏 仅余 妄想 ...
3    1 . 终于 ， 轮 到 我们 仰望 星空 。 2 . 后 启示录 死亡 废墟 ， 赛博 朋...
4    一个 悲伤 的 故事 ： 太阳 都 要 毁灭 ， 地球 都 要 流浪 了 ， 我国 的 校服...
Name: cutted_comment, dtype: object

In [30]:
X.head()

comments  \
0  真为吴京的演技尴尬，总是摆出一副大义凌然的样子，好奇为什么刘的作品中总有这种傻逼般的圣母存在...   
1  电影比预期要更恢弘磅礴，晨昏线过后的永夜、火种计划、让地球流浪、木星推动地球…等等大小设定，...   
2  还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...   
3  1.终于，轮到我们仰望星空。2.后启示录死亡废墟，赛博朋克地下城，以及烟波浩渺的末日想象，缔...   
4            一个悲伤的故事：太阳都要毁灭，地球都要流浪了，我国的校服还是这么丑......   

                                      cutted_comment  
0  真为 吴京 的 演技 尴尬 ， 总是 摆 出 一副 大义 凌然 的 样子 ， 好奇 为什么 ...  
1  电影 比 预期 要 更 恢弘 磅礴 ， 晨昏 线 过后 的 永夜 、 火种 计划 、 让 地...  
2  还 能 更 土 更 儿戏 一点 吗 ？ 毫无 思考 仅靠 煽动 ， 毫无 敬畏 仅余 妄想 ...  
3  1 . 终于 ， 轮 到 我们 仰望 星空 。 2 . 后 启示录 死亡 废墟 ， 赛博 朋...  
4  一个 悲伤 的 故事 ： 太阳 都 要 毁灭 ， 地球 都 要 流浪 了 ， 我国 的 校服...

In [31]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [32]:
X_train.shape

(22500, 2)

In [33]:
X_train.head()

comments  \
26340  真为吴京的演技尴尬，总是摆出一副大义凌然的样子，好奇为什么刘的作品中总有这种傻逼般的圣母存在...   
3877   充斥着模仿的痕迹，某些镜头直接地心引力同款，另外就是画质极渣的摄影以及播放卡顿。宏大主题配以...   
27081  1.终于，轮到我们仰望星空。2.后启示录死亡废墟，赛博朋克地下城，以及烟波浩渺的末日想象，缔...   
5440   还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...   
22164  还能更土更儿戏一点吗？毫无思考仅靠煽动，毫无敬畏仅余妄想。好的科幻片应该首先承认人类的无知，...   

                                          cutted_comment  
26340  真为 吴京 的 演技 尴尬 ， 总是 摆 出 一副 大义 凌然 的 样子 ， 好奇 为什么 ...  
3877   充斥 着 模仿 的 痕迹 ， 某些 镜头 直接 地心引力 同款 ， 另外 就是 画质 极渣 ...  
27081  1 . 终于 ， 轮 到 我们 仰望 星空 。 2 . 后 启示录 死亡 废墟 ， 赛博 朋...  
5440   还 能 更 土 更 儿戏 一点 吗 ？ 毫无 思考 仅靠 煽动 ， 毫无 敬畏 仅余 妄想 ...  
22164  还 能 更 土 更 儿戏 一点 吗 ？ 毫无 思考 仅靠 煽动 ， 毫无 敬畏 仅余 妄想 ...

In [34]:
y_train.shape

(22500,)

In [35]:
X_test.shape

(7500, 2)

In [36]:
y_test.shape

(7500,)

In [37]:
def get_custom_stopwords(stop_words_file):
    with open(stop_words_file) as f:
        stopwords = f.read()
    stopwords_list = stopwords.split('\n')
    custom_stopwords_list = [i for i in stopwords_list]
    return custom_stopwords_list

In [38]:
stop_words_file = "stopwords.txt"
stopwords = get_custom_stopwords(stop_words_file)

In [39]:
stopwords[-10:]

['如下', '汝', '三番两次', '三番五次', '三天两头', '瑟瑟', '沙沙', '上', '上来', '上去']

In [40]:
from sklearn.feature_extraction.text import CountVectorizer

In [41]:
vect = CountVectorizer()

In [42]:
term_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_comment).toarray(), columns=vect.get_feature_names())

In [43]:
term_matrix.head()

100  30  89  bb  bgm  eason  frost  punk  一下  一丝 ...  鞋里  预期  题材  飞船  首先  \
0    0   0   0   0    0      0      0     0   0   0 ...   0   0   1   0   0   
1    0   0   0   0    0      0      0     0   0   0 ...   0   0   0   0   0   
2    0   0   0   0    0      0      0     0   0   0 ...   0   0   0   0   0   
3    0   0   0   0    0      0      0     0   0   0 ...   0   0   0   0   1   
4    0   0   0   0    0      0      0     0   0   0 ...   0   0   0   0   1   

   首部  骄傲  高分  高空  鼓励  
0   0   0   0   0   0  
1   0   0   0   0   0  
2   0   0   0   0   0  
3   0   0   0   0   0  
4   0   0   0   0   0  

[5 rows x 707 columns]

In [44]:
term_matrix.shape

(22500, 707)

In [45]:
vect = CountVectorizer(stop_words=frozenset(stopwords))

In [46]:
term_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_comment).toarray(), columns=vect.get_feature_names())

In [47]:
term_matrix.head()

100  30  89  bb  bgm  eason  frost  punk  一丝  一分 ...  零下  鞋里  预期  题材  飞船  \
0    0   0   0   0    0      0      0     0   0   0 ...   0   0   0   1   0   
1    0   0   0   0    0      0      0     0   0   0 ...   0   0   0   0   0   
2    0   0   0   0    0      0      0     0   0   0 ...   0   0   0   0   0   
3    0   0   0   0    0      0      0     0   0   0 ...   0   0   0   0   0   
4    0   0   0   0    0      0      0     0   0   0 ...   0   0   0   0   0   

   首部  骄傲  高分  高空  鼓励  
0   0   0   0   0   0  
1   0   0   0   0   0  
2   0   0   0   0   0  
3   0   0   0   0   0  
4   0   0   0   0   0  

[5 rows x 582 columns]

In [48]:
max_df = 0.8 # 在超过这一比例的文档中出现的关键词（过于平凡），去除掉。
min_df = 3 # 在低于这一数量的文档中出现的关键词（过于独特），去除掉。

In [49]:
vect = CountVectorizer(max_df = max_df,
                       min_df = min_df,
                       token_pattern=u'(?u)\\b[^\\d\\W]\\w+\\b',
                       stop_words=frozenset(stopwords))

In [50]:
term_matrix = pd.DataFrame(vect.fit_transform(X_train.cutted_comment).toarray(), columns=vect.get_feature_names())

In [51]:
term_matrix.head()

bb  bgm  eason  frost  punk  一丝  一分  一副  一同  一塌糊涂 ...  零下  鞋里  预期  题材  飞船  \
0   0    0      0      0     0   0   0   1   0     0 ...   0   0   0   1   0   
1   0    0      0      0     0   0   0   0   0     0 ...   0   0   0   0   0   
2   0    0      0      0     0   0   0   0   0     0 ...   0   0   0   0   0   
3   0    0      0      0     0   0   0   0   0     0 ...   0   0   0   0   0   
4   0    0      0      0     0   0   0   0   0     0 ...   0   0   0   0   0   

   首部  骄傲  高分  高空  鼓励  
0   0   0   0   0   0  
1   0   0   0   0   0  
2   0   0   0   0   0  
3   0   0   0   0   0  
4   0   0   0   0   0  

[5 rows x 579 columns]

In [52]:
from sklearn.naive_bayes import MultinomialNB
nb = MultinomialNB()

In [53]:
from sklearn.pipeline import make_pipeline
pipe = make_pipeline(vect, nb)

In [54]:
pipe.steps

[('countvectorizer',
  CountVectorizer(analyzer='word', binary=False, decode_error='strict',
          dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
          lowercase=True, max_df=0.8, max_features=None, min_df=3,
          ngram_range=(1, 1), preprocessor=None,
          stop_words=frozenset({'', '咦', '已经', '其余', '往', '除却', '兮', '从优', '▲', '孰料', '才', '移动', '到', '己', '出于', '曾', '趁着', '临', '而且', '得出', '时候', '大多', '［②ａ］', '运用', '等', '可见', '什麽', '只是', '其实', '［②Ｂ］', '任', '谨', '即若', '再次', '皆可', '大量', '联袂', '＞λ', '得到', '无', '背靠背', '周围', '正如', '极其', '不仅仅是', '毕竟', '一一', '窃',...面', '巴', '奇', '挨门挨户', '尽然', '不怕', '［④ｂ］', '７', '［④］', '却不', '况且', '纵', '较比', '将才', '居然', '『', '经常'}),
          strip_accents=None, token_pattern='(?u)\\b[^\\d\\W]\\w+\\b',
          tokenizer=None, vocabulary=None)),
 ('multinomialnb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))]

In [55]:
from sklearn.cross_validation import cross_val_score
cross_val_score(pipe, X_train.cutted_comment, y_train, cv=5, scoring='accuracy').mean()

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


1.0

In [56]:
pipe.fit(X_train.cutted_comment, y_train)

Pipeline(memory=None,
     steps=[('countvectorizer', CountVectorizer(analyzer='word', binary=False, decode_error='strict',
        dtype=<class 'numpy.int64'>, encoding='utf-8', input='content',
        lowercase=True, max_df=0.8, max_features=None, min_df=3,
        ngram_range=(1, 1), preprocessor=None,
        stop_words=...e, vocabulary=None)), ('multinomialnb', MultinomialNB(alpha=1.0, class_prior=None, fit_prior=True))])

In [57]:
pipe.predict(X_test.cutted_comment)

array([0, 1, 1, ..., 0, 0, 1], dtype=int64)

In [58]:
y_pred = pipe.predict(X_test.cutted_comment)

In [59]:
from sklearn import metrics

In [60]:
metrics.accuracy_score(y_test, y_pred)

1.0

In [61]:
metrics.confusion_matrix(y_test, y_pred)

array([[4805,    0],
       [   0, 2695]], dtype=int64)

In [62]:
from snownlp import SnowNLP
def get_sentiment(text):
    return SnowNLP(text).sentiments

In [63]:
y_pred_snownlp = X_test.comments.apply(get_sentiment)

In [64]:
y_pred_snownlp_normalized = y_pred_snownlp.apply(lambda x: 1 if x>0.5 else 0)

In [65]:
y_pred_snownlp_normalized[:5]

10747    1
12573    1
29676    1
8856     1
21098    0
Name: comments, dtype: int64

In [72]:
metrics.accuracy_score(y_test, y_pred_snownlp_normalized)

0.424

In [73]:
metrics.confusion_matrix(y_test, y_pred_snownlp_normalized)

array([[16, 72],
       [ 0, 37]], dtype=int64)